@rem
@rem Placeholder for the Windows Gradle wrapper launcher.
@rem
@rem The real gradlew.bat plus gradle-wrapper.jar will be generated by running
@rem   gradle wrapper --gradle-version 8.10.2
@rem or by opening the project in Android Studio (which performs the same step
@rem on first sync). The JAR is a binary file so it is not included in this
@rem scaffold.

@echo gradlew.bat placeholder: run "gradle wrapper" or open the project in Android Studio to generate the real wrapper.
@exit /b 1
